<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>DataNro</RootNamespace>
        <AssemblyName>DataNro.HeadlessClient</AssemblyName>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

</Project>
